version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Starting Docker...
      - docker info

  build:
    commands:
      - echo Building Docker image...
      - docker build -t mi-app ./app

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
